print("this is main branch")
print("this is added line after creating branch 1")
print("now this is final and i am going to merge both branches")
print("lets see!!!!..........")
print("this is line in same place of main branch to make conflict")
print("this is updated line after creating branch 2")
